added full maket
VladT8/fe-46-tsishuk pull request #1
Opened 2023-02-07 07:57 UTC by VladT8

2023-02-07 10:42 UTC, UladTeachMeSkills requested changes

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                        <img src="./icons/IT.svg" alt="logo">
Можно было одним изображением сделать

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                     <a href="index.html">
Просто # влепи

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                  <input type="text" placeholder="Name" required>
Стилезуй input так чтобы у него была нижняя граница, тогда уберётся hr

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                  <button class="button-type-two">Get Started</button>
У кнопки должен быть тип submit

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                     <img src="./icons/triangle.svg" alt="">
Пустой alt

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                     <img src="./img/customer_ava_1.png" alt="avatar">
same

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                     <img src="./icons/triangle.svg" alt="">
same

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +                     <img src="./icons/triangle.svg" alt="">
same

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +            <button class="button-type-one button-type-one_center">Download</button>
укажи тип

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +               <input type="text" placeholder="Name" required>
same ( стиль инпута, вместо hr  )

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +         <button class="button-type-tree button-type-tree_contact">Send Message</button>
Это всё - одна форма

2023-02-07 10:42 UTC, UladTeachMeSkills commented on axit-project/index.html
> +         <button class="button-type-tree button-type-tree_contact">Send Message</button>
Тип

2023-02-07 16:25 UTC, VladT8 commented on axit-project/index.html
> +         <button class="button-type-tree button-type-tree_contact">Send Message</button>
пофиксил все, и обновил ветку

2023-02-08 15:58 UTC, UladTeachMeSkills approved these changes

2023-02-08 15:58 UTC, UladTeachMeSkills commented on axit-project/styles/buttons.css
> +	font-family: 'Open Sans';;
Лишняя точка с запятой

2023-02-08 15:58 UTC, UladTeachMeSkills commented on axit-project/styles/reviews.css
> +/* Хотел треугольник добавить так, но он привязывается к p , а не к div почему-то
position relative у родителя
position absolute у псевдоэлемента

2023-02-08 17:17 UTC, VladT8 commented on axit-project/styles/reviews.css
> +/* Хотел треугольник добавить так, но он привязывается к p , а не к div почему-то
пофиксил + 2 новых коммита

2023-02-08 17:17 UTC, VladT8 commented on axit-project/styles/reviews.css
> +/* Хотел треугольник добавить так, но он привязывается к p , а не к div почему-то
если все ок, то замержу и сделаю новую ветку для работы над адаптацией

2023-02-08 20:32 UTC, UladTeachMeSkills approved these changes

2023-02-08 20:32 UTC, UladTeachMeSkills commented on axit-project/index.html
> +            <a target="_blank" href="https://www.axurethemes.com/"><p>© 2015 Axure Themes</p></a>
Копирайт это не ссылка :)

2023-02-09 12:42 UTC, merged