Adaptiv
VladT8/fe-46-tsishuk pull request #2
Opened 2023-02-14 22:59 UTC by VladT8

не получилось сделать нормально меню-бургер и слайдер в reviews. пока закоментировал, позже попробую доделать

2023-02-15 13:13 UTC, UladTeachMeSkills requested changes

2023-02-15 13:13 UTC, UladTeachMeSkills commented on axit-project/js/index.js
> +});
Ты же наверное в курсе что это jQuery? Не прокатит :(

2023-02-15 13:13 UTC, UladTeachMeSkills commented on axit-project/styles/contact.css
> +	width: calc(570/1170*100%);
Чем это отличается от 0.49*100%?

2023-02-15 16:27 UTC, VladT8 commented on axit-project/js/index.js
> +});
убрал

2023-02-15 16:27 UTC, VladT8 commented on axit-project/styles/contact.css
> +	width: calc(570/1170*100%);
так точнее немного. а данные из макета для десктопа. 570 ширина дива, 1170 - контейнер

2023-02-16 09:07 UTC, UladTeachMeSkills approved these changes

2023-02-16 17:44 UTC, merged